#!/bin/bash -l

# ~~~~~~~  A. PBS-related part  ~~~~~~~

#PBS -A lp_h_mdaw
#PBS -l nodes=1:ppn=6
#PBS -l walltime=01:00:00
#PBS -l pmem=5gb
#PBS -m bae

# >>>>>    Replace my email with yours    <<<<<<<
#PBS -M haris-zaf@hcmr.gr
  


# ~~~~~~~  B. PEMA execution command  ~~~~~~~

# >>>>>    Replace my path to my_analysis with yours    <<<<<<<
singularity run -B /scratch/leuven/341/vsc34189/pema-mdawo/my_analysis:/mnt/analysis /ddn1/vol1/site_scratch/leuven/314/vsc31426/pema_v.2.0.3.sif

